spring.application.name=LoginService

server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/usermanagement_db
spring.datasource.username=postgres
spring.datasource.password=Astroworld@24
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=fnb-bootcamp-super-secret-key-2024-make-it-long
jwt.expiration=86400000