spring.application.name=UserManagementService


server.port=8081


# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/usermanagement_db
spring.datasource.username=postgres
spring.datasource.password=Astroworld@24
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
